# Dang Thanh Vu - 197796

In [1]:
import numpy as np

def edit_distance(src, dst):
    m = len(src)
    n = len(dst)
    template = np.zeros((m + 1, n + 1))
    s = template[0, 0]
    for i in range(1, m + 1):
        if(src[i - 1] != dst[0]):
            s = s + 1
        template[i, 0] = s
    s = template[0, 0]
    path = []
    for i in range(1, n + 1):
        if(src[0] != dst[i - 1]):
            s = s + 1
        template[0, i] = s
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            if(src[i - 1] == dst[j - 1]):
                template[i, j] = template[i - 1, j - 1]
            else:
                template[i, j] = np.min([template[i - 1, j - 1], template[i, j - 1], template[i - 1, j]]) + 1           
    return template[m, n], template 
def find_path(template):
    m, n = template.shape[:]
    m = m - 1
    n = n - 1
    path = [(m, n)]
    while(m > 0 and n > 0):
        argmin = np.argmin([template[m - 1, n - 1], template[m, n - 1], template[m - 1, n]])
        if(argmin == 0):
            path.append((m - 1, n - 1))
            m = m - 1
            n = n - 1
        elif(argmin == 1):
            path.append((m, n - 1))
            n = n - 1
        else:
            path.append((m - 1, n))
            m = m - 1
    return path

In [2]:
d, template = edit_distance("template", "teplatte")
print("edit distance: ", d)
print(template)
path = find_path(template)
print(path)

edit distance:  2.0
[[0. 0. 1. 2. 3. 4. 4. 4. 5.]
 [0. 0. 1. 2. 3. 4. 4. 4. 5.]
 [1. 1. 0. 1. 2. 3. 4. 5. 4.]
 [2. 2. 1. 1. 2. 3. 4. 5. 5.]
 [3. 3. 2. 1. 2. 3. 4. 5. 6.]
 [4. 4. 3. 2. 1. 2. 3. 4. 5.]
 [5. 5. 4. 3. 2. 1. 2. 3. 4.]
 [5. 5. 5. 4. 3. 2. 1. 2. 3.]
 [6. 6. 5. 5. 4. 3. 2. 2. 2.]]
[(8, 8), (7, 7), (7, 6), (6, 5), (5, 4), (4, 3), (3, 2), (2, 2), (1, 1), (0, 0)]


In [3]:
d, template = edit_distance("impose", "igposre")
print("edit distance: ", d)
print(template)
path = find_path(template)
print(path)

edit distance:  2.0
[[0. 0. 1. 2. 3. 4. 5. 6.]
 [0. 0. 1. 2. 3. 4. 5. 6.]
 [1. 1. 1. 2. 3. 4. 5. 6.]
 [2. 2. 2. 1. 2. 3. 4. 5.]
 [3. 3. 3. 2. 1. 2. 3. 4.]
 [4. 4. 4. 3. 2. 1. 2. 3.]
 [5. 5. 5. 4. 3. 2. 2. 2.]]
[(6, 7), (5, 6), (5, 5), (4, 4), (3, 3), (2, 2), (1, 1), (0, 0)]


In [4]:
d, template = edit_distance("ignore", "igposre")
print("edit distance: ", d)
print(template)
path = find_path(template)
print(path)

edit distance:  2.0
[[0. 0. 1. 2. 3. 4. 5. 6.]
 [0. 0. 1. 2. 3. 4. 5. 6.]
 [1. 1. 0. 1. 2. 3. 4. 5.]
 [2. 2. 1. 1. 2. 3. 4. 5.]
 [3. 3. 2. 2. 1. 2. 3. 4.]
 [4. 4. 3. 3. 2. 2. 2. 3.]
 [5. 5. 4. 4. 3. 3. 3. 2.]]
[(6, 7), (5, 6), (4, 5), (4, 4), (3, 3), (2, 2), (1, 1), (0, 0)]


In [5]:
d, template = edit_distance("restore", "igposre")
print("edit distance: ", d)
print(template)
path = find_path(template)
print(path)

edit distance:  5.0
[[0. 1. 2. 3. 4. 5. 5. 6.]
 [1. 1. 2. 3. 4. 5. 5. 6.]
 [2. 2. 2. 3. 4. 5. 6. 5.]
 [3. 3. 3. 3. 4. 4. 5. 6.]
 [4. 4. 4. 4. 4. 5. 5. 6.]
 [5. 5. 5. 5. 4. 5. 6. 6.]
 [6. 6. 6. 6. 5. 5. 5. 6.]
 [7. 7. 7. 7. 6. 6. 6. 5.]]
[(7, 7), (6, 6), (5, 5), (4, 4), (3, 3), (2, 2), (1, 1), (0, 0)]
